### ISSUE TITLE
Does not compile with Clang (AppleClang 7.0.2.7000181, Xcode 7.2, OS X 10.11.4, i7 Sandy Bridge)

### ISSUE THREAD

**Issue by zeroum** [callmephil/SunWellCore#74]
```
/xxx/sunwellcore/dep/recastnavigation/Detour/DetourNavMesh.h:33:32: fatal error: 
      typedef redefinition with different types ('uint64_t' (aka
      'unsigned long long') vs 'ACE_UINT64' (aka 'unsigned long'))
    typedef uint64_t           uint64;
                               ^
In file included from /xxx/sunwellcore/src/server/game/PrecompiledHeaders/gamePCH.h:3:
In file included from /xxx/sunwellcore/src/server/game/Server/WorldSocket.h:41:
In file included from /xxx/sunwellcore/src/server/shared/Common.h:62:
/xxx/sunwellcore/src/server/shared/Define.h:85:20: note: 
      previous definition is here
typedef ACE_UINT64 uint64;
                   ^
```

Extra: Also lots of deprecation warnings for this function:

```
/xxx/sunwellcore/src/server/shared/Common.h:137:45: warning: 
      'finite' is deprecated: first deprecated in OS X 10.9
      [-Wdeprecated-declarations]
inline float finiteAlways(float f) { return finite(f) ? f : 0.0f; }
                                            ^
```

**Comment by FrancescoBorzi** [comment]
hi @zeroum try this https://github.com/azerothcore/azerothcore-wotlk/commit/b96f058c175657aa85047f4200196bdd952c9888
